### ISSUE TITLE
Just what I was looking for! 

### ISSUE THREAD

**Issue by MostHated** [hkdb/GoGUI#1]
Hey there,   
This is great, just what I was hoping to find. I see it is based off of another repo (webview), I would imagine that, that is where I should look for more information on usage and capabilities? Is this repo going to have any additional features on top of the webview, or is this more just a demonstration of what it can do?

Thanks,
-MH

**Comment by hkdb** [comment]
Hi there,

I put together this repo because at work, we build a lot of utility apps for both client projects and internal use so everything so-far is more geared towards making a template for those apps here rather than building a forked Webview library. ie. [Densify](https://github.com/hkdb/Densify) being GTK heavy has been painful for us to compile into a single binary in Windows. The idea behind switching to Go and Webview is that we can build responsive cross platform utility applications just like Densify very quickly. Given that, After adding a progress bar component and doing some further testing along with some small tweaks, I will probably release and leave it as is for a while and focus more on using it to build apps until I come up with more "repetitive needs" that I can incorporate into this template.

You will definitely want to look at the [webview](https://github.com/zserge/webview) repo to learn more about usage and capabilities and [go-bindata](https://github.com/jteeuwen/go-bindata) as well on how  including binary data into the build works so that you are well equipped to make use of this template effectively.

Hope this little template will help with whatever project you are thinking of working on and I would love to hear about it if you build something off of it! :)

Cheers,

-J

**Comment by MostHated** [comment]
Sorry for the late reply. I was out of town all week. Your intention with the repo definitely makes sense and I do very much appreciate you sharing it as well as the great info and links. I very much like repos like this, which demonstrate several different aspects and seeing how people go about things. I actually did something quite similar with a repo I made for a cli gui. (https://github.com/instance-id/GoUI), though it was less of a generalized demonstration and testing of things as I had a specific goal in mind, but I definitely wanted to share it so others might be able to benefit.

I thank you again and favorited this so I can reference it down the road!
Thanks,
-MH
